language: objective-c
os: osx
osx_image: xcode8.1

-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    xcodebuild clean test -project ./YJRead.xcodeproj -scheme YJRead -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -enableCodeCoverage YES | xcpretty

after_success:
- |
   bash <(curl -s https://codecov.io/bash)
        

