
name: build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 8']
        swift-version: [5.3]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Testing
        run: |
          xcodebuild clean test -project YJRead.xcodeproj -scheme YJRead -destination "${destination}" -enableCodeCoverage YES
          bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
        env: 
           destination: ${{ matrix.destination }}
           CODECOV_TOKEN: ${{ secrets.codecov_token }}
           SWIFT_VERSION: ${{ matrix.swift-version }}
